### ISSUE TITLE
generate wrong ID if the headings content `.`

### ISSUE THREAD

**Issue by Snowpee** [willin/gitbook-plugin-atoc#1]
eg. 
## 1.1 title

the link generated by this plugin is like this: `1.-1-title`, but the heading ID is `1-1-title`.

**Comment by willin** [comment]
I will look into it asap.

**Comment by willin** [comment]
Try out this: @Snowpee

Replace `index.js` Line 9:

``` js
 return encodeURI(str.toLowerCase()).replace(/%20/g, '-').replace(/\./g,'');
```

**Comment by willin** [comment]
thx
