### ISSUE TITLE
This plugin takes wrong items for the TOC

### ISSUE THREAD

**Issue by tianshuo** [willin/gitbook-plugin-atoc#3]
This file without the `<!-- toc -->` tag, actually creates a toc.

```
1. Test
    * Something is wrong
    * [node](http://nodejs.org/) 
```

See this image
![image](https://cloud.githubusercontent.com/assets/232424/16170171/5c3015b0-357c-11e6-98a1-e873f506ebe2.png)

**Comment by willin** [comment]
yes, thx

**Comment by willin** [comment]
https://github.com/willin/gitbook-plugin-atoc/commit/1e206ff588f9d2196a93fe49b3571ecae0d91c15

**Comment by willin** [comment]
ok
