### ISSUE TITLE
GitBook Community in Google+

### ISSUE THREAD

**Issue by aleen42** [willin/gitbook-plugin-atoc#5]
Hi willin,

I am Aleen (https://github.com/aleen42) , and the founder of GitBook Community in Google+: https://plus.google.com/communities/110696788983472771007, which aims to sharing books or plugins of GitBook, talking anything about it as well. Here I am sincerely inviting you to join us.  :punch:

**Comment by willin** [comment]
thx

**Comment by aleen42** [comment]
@willin You're welcome!
