### ISSUE TITLE
No class name created for ul element

### ISSUE THREAD

**Issue by Eymux** [willin/gitbook-plugin-atoc#6]
Gitbook 3.2.0
gitbook-plugin-atoc 1.0.1

``` json
    "pluginsConfig": {
        "atoc": {
        "addClass": true,
        "className": "toc"
        }
    }
```

The plugin creates a plain &lt;ul&gt; tag with no class name.

**Comment by Banbury** [comment]
Sorry, my bad. I didn't understand how the plugin works.

**Comment by Eymux** [comment]
Sorry, I figured it out myself.
