### ISSUE TITLE
Can't link to anchor if the id is Chinese 

### ISSUE THREAD

**Issue by Snowpee** [willin/gitbook-plugin-atoc#8]
The heading id is decode to utf 8, but the link in toc not.

![屏幕快照 2017-04-05 下午3.11.22.png](http://hb-prd.b0.upaiyun.com/images/2017/04/f0cbc225e6ff0cffc254f0dfd7995b2c.png)

![屏幕快照 2017-04-05 下午3.12.13.png](http://hb-prd.b0.upaiyun.com/images/2017/04/ce67ad47e1c5105eeaf63193d36f6eb8.png)

**Comment by willin** [comment]
it's the same. what browser are you using?

**Comment by Snowpee** [comment]
Chrome

**Comment by willin** [comment]
![wx20170721-171249](https://user-images.githubusercontent.com/1890238/28457210-e4ca3108-6dca-11e7-969a-9de0a37055fc.png)
![wx20170721-171216](https://user-images.githubusercontent.com/1890238/28457211-e4cfbdc6-6dca-11e7-92d7-206d4c02624b.png)

- CLI version: 2.3.0
- GitBook version: 3.2.2
- Chrome:  61
